# Generated by Django 3.2.4 on 2021-06-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multicat', '0002_auto_20210630_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='c_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent',)},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
